<a href="https://colab.research.google.com/github/srahul101082/TensorFlow/blob/master/Tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

In [6]:
x=tf.constant((2.0))
print(x)

tf.Tensor(2.0, shape=(), dtype=float32)


In [9]:
x=tf.constant([[1,2,3],[4,5,6]],shape=(3, 2))
print(x)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [14]:
x=tf.ones((3,3),dtype='float32')
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [15]:
x=tf.eye(3,3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [19]:
x=tf.random.normal((3,3),mean=0,stddev=1)
print(x)

tf.Tensor(
[[-0.55196345 -2.0357246  -0.94826406]
 [ 0.08970811 -1.3481249   2.1821072 ]
 [-0.8224901   1.2545199  -0.36341992]], shape=(3, 3), dtype=float32)


In [21]:
x=tf.random.uniform((1,3),minval=0,maxval=1)
print(x)

tf.Tensor([[0.12100136 0.9553201  0.93694913]], shape=(1, 3), dtype=float32)


In [26]:
a=tf.constant([1,2,3])
b=tf.constant([9,8,7])
result=tf.add(a,b)
print(result)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [29]:
sub=a-b
print(sub)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [35]:
z=tf.tensordot(a,b, axes=0)
print(z)

tf.Tensor(
[[ 9  8  7]
 [18 16 14]
 [27 24 21]], shape=(3, 3), dtype=int32)
