<a href="https://colab.research.google.com/github/srahul101082/TensorFlow/blob/master/tensorflow_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.4.0


In [3]:
mnist=tf.keras.datasets.mnist
(x_train, y_train),(x_test,y_test)=mnist.load_data()
x_train,x_test=x_train/255.0, x_test/255.0

In [4]:
model=tf.keras.models.Sequential([
tf.keras.layers.Flatten(input_shape=(28,28)),  
tf.keras.layers.Dense(64,activation='relu'),
tf.keras.layers.Dropout(0.2),
tf.keras.layers.Dense(10)                   
                                  
])

In [8]:
predictions=model(x_train[:1]).numpy()
predictions


array([[ 0.6412415 ,  0.10944999,  0.7705423 ,  0.1718799 ,  0.03215746,
         0.3701129 , -0.15424056, -0.71416974, -0.13750933, -0.15597378]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.15933417, 0.09361702, 0.18132745, 0.09964781, 0.08665369,
        0.12149524, 0.07191765, 0.04108291, 0.07313103, 0.0717931 ]],
      dtype=float32)

In [10]:
loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
loss_fn(y_train[:1], predictions).numpy()

2.10788

In [12]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics='accuracy')

In [13]:
model.fit(x_train, y_train, epochs=5,verbose=1)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.5689 - accuracy: 0.8327
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2041 - accuracy: 0.9397
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1589 - accuracy: 0.9529
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1318 - accuracy: 0.9600
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1153 - accuracy: 0.9643


In [14]:
model.evaluate(x_test,y_test, verbose=2)

313/313 - 0s - loss: 0.0973 - accuracy: 0.9699


[0.09728208929300308, 0.9699000120162964]

In [15]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.9056831e-07, 3.6471221e-08, 9.2840683e-06, 3.1086174e-04,
        1.1767537e-10, 3.2104884e-07, 2.2404965e-14, 9.9966717e-01,
        7.8822254e-08, 1.1695002e-05],
       [3.9739740e-07, 6.7046203e-05, 9.9977475e-01, 1.3922641e-04,
        4.0727703e-15, 1.0360494e-05, 6.8276208e-06, 3.6176676e-11,
        1.4374542e-06, 5.5242811e-13],
       [1.9074675e-07, 9.9909949e-01, 1.5234796e-04, 7.4167925e-05,
        1.1577212e-05, 2.0652846e-05, 1.2698841e-05, 3.5995766e-04,
        2.6619766e-04, 2.7574417e-06],
       [9.9981171e-01, 1.9344550e-10, 1.7146882e-05, 2.3909041e-07,
        6.0384281e-08, 1.8965917e-05, 2.2454211e-05, 1.2897106e-04,
        7.6306392e-08, 3.6741500e-07],
       [1.9909842e-04, 2.6982105e-08, 1.0388353e-04, 2.6247676e-06,
        9.8588043e-01, 2.6970132e-05, 7.0701084e-05, 2.6743041e-04,
        1.3475431e-05, 1.3435352e-02]], dtype=float32)>